# bindings
# set-option default-command "zsh --login"
set -g prefix C-a
set -g base-index 1
set -g display-panes-time 3000
setw -g pane-base-index 1
set-option -sa terminal-features ',xterm*:Tc'
bind C-a send-prefix
unbind C-b

bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R
bind g last-window

bind c new-window -c "#{pane_current_path}"
bind '"' split-window -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"

# tmux navigation
setw -g mode-keys vi
bind-key -T copy-mode-vi MouseDragEnd1Pane send-keys -X copy-selection -x
bind-key -T copy-mode-vi y send-keys -X copy-selection -x

# mouse support
set -g mouse on
set -g status-position top

# renumber panes
set-option -g renumber-windows on

# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-battery'
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'catppuccin/tmux#v2.1.2'

# theme
set -g @catppuccin_flavor 'mocha'
set -g @catppuccin_window_status_enable "yes"
set -g @catppuccin_window_flags "icon"
set -g @catppuccin_window_number_color "#77a3f8"
set -g @catppuccin_window_current_number_color "#f6a375"
set -ogq @catppuccin_window_text " #W"
set -g @catppuccin_window_current_text " #W"

# set -g @catppuccin_window_default_text " #W "
set -g status-right-length 100
set -g status-left-length 100
set -g status-left ""
set -gF status-right "#{E:@catppuccin_status_session}#{E:@catppuccin_status_battery}#{E:@catppuccin_status_date_time}"
# set -ag status-right "#{E:@catppuccin_status_session}"
# set -agF status-right "#{E:@catppuccin_status_battery}"
# set -agF status-right "#{E:@catppuccin_status_date_time}"

# navigator keybindings
set -g @vim_navigator_mapping_left "M-Left M-h"  # use C-h and C-Left
set -g @vim_navigator_mapping_right "M-Right M-l"
set -g @vim_navigator_mapping_up "M-k"
set -g @vim_navigator_mapping_down "M-j"

# set -g @plugin 'github_username/plugin_name'
# set -g @plugin 'github_username/plugin_name#branch'
# set -g @plugin 'git@github.com:user/plugin'
# set -g @plugin 'git@bitbucket.com:user/plugin'
# set -g @plugin 'egel/tmux-gruvbox'
# set -g @tmux-gruvbox 'dark' # or 'light'
# set -g @plugin 'dracula/tmux'
# set -g @dracula-plugins "battery cpu-usage ram-usage time"
# set -g @dracula-show-powerline true
# set -g @dracula-show-left-icon session
# set -g @dracula-battery-label "Battery"
# set -g @dracula-show-timezone false
#
# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'


