#!/bin/bash

result=$(lsblk -l | grep disk | grep "^nvme0n1" -v | grep "/run/media" -v | dmenu -p 'Select volume to mount' -l 5 | cut -c 1-4)

if test -z "$result" 
then
    	echo "empty"
else
	udisksctl mount -b /dev/$result && notify-send "Drive mounted"
fi

