#!/bin/bash

configs=("Dual Monitor" "Single Monitor Ext" "Single Monitor Prime")

result=$(printf "%s\n" "${configs[@]}" | fuzzel -d -p 'Select Display Configuration:')

if test -z "$result"
then
    echo "nothing selected"
else  
    case "$result" in
        "Dual Monitor")
            # Add the command to configure dual monitor setup
            # echo "Configuring Dual Monitor setup..."
            # hyprctl dispatch setdualmonitorconfig
            hyprctl eval 'hl.monitor({ output = "DP-2", disabled = false })'
            hyprctl eval 'hl.monitor({ output = "eDP-1", disabled = false })'
            hyprctl eval 'hl.monitor({ output = "DP-2", mode = "prefered", position = "0x0", scale = 1.07 })'
            hyprctl eval 'hl.monitor({ output = "eDP-1", mode = "prefered", position = "0x1440", scale = 1.6 })'
            ;;
        "Single Monitor Prime")
            # Add the command to configure single monitor setup
            # echo "Configuring Single Monitor setup..."
            # hyprctl dispatch setsinglemonitorconfig
            hyprctl eval 'hl.monitor({ output = "eDP-1", disabled = false })'
            hyprctl eval 'hl.monitor({ output = "DP-2", disabled = true })'
            hyprctl eval 'hl.monitor({ output = "eDP-1", mode = "prefered", position = "0x1440", scale = 1.6 })'
            ;;
        "Single Monitor Ext")
            # Add the command to configure single monitor setup
            # echo "Configuring Single Monitor setup..."
            # hyprctl dispatch setsinglemonitorconfig
            hyprctl eval 'hl.monitor({ output = "DP-2", disabled = false })'
            hyprctl eval 'hl.monitor({ output = "DP-2", mode = "prefered", position = "0x0", scale = 1.07 })'
            hyprctl eval 'hl.monitor({ output = "eDP-1", disabled = true })'
            ;;
        *)
            echo "Unknown configuration selected"
            ;;
    esac
fi

