#!/bin/bash

configs=("Dual Monitor" "Single Monitor Ext" "Single Monitor Prime")

result=$(printf "%s\n" "${configs[@]}" | fuzzel -d -p 'Select Display Configuration:')

if test -z "$result"
then
    echo "nothing selected"
else  
    case "$result" in
        "Dual Monitor")
            # Add the command to configure dual monitor setup
            # echo "Configuring Dual Monitor setup..."
            # hyprctl dispatch setdualmonitorconfig
            hyprctl keyword monitor HDMI-A-1,preferred,auto,1
            hyprctl keyword monitor eDP-1,preferred,auto,1.6
            ;;
        "Single Monitor Prime")
            # Add the command to configure single monitor setup
            # echo "Configuring Single Monitor setup..."
            # hyprctl dispatch setsinglemonitorconfig
            hyprctl keyword monitor HDMI-A-1,disable
            hyprctl keyword monitor eDP-1,preferred,auto,1.6
            ;;
        "Single Monitor Ext")
            # Add the command to configure single monitor setup
            # echo "Configuring Single Monitor setup..."
            # hyprctl dispatch setsinglemonitorconfig
            hyprctl keyword monitor HDMI-A-1,preferred,auto,1
            hyprctl keyword monitor eDP-1,disable
            ;;
        *)
            echo "Unknown configuration selected"
            ;;
    esac
fi

